apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: data-processing
data:
  rabbitmq.conf: |
    ## Cluster formation
    cluster_formation.peer_discovery_backend = k8s
    cluster_formation.k8s.host = kubernetes.default.svc.cluster.local
    cluster_formation.k8s.address_type = hostname
    cluster_formation.node_cleanup.interval = 30
    cluster_formation.node_cleanup.only_log_warning = true
    cluster_partition_handling = autoheal
    
    ## Queue configuration
    queue_master_locator = min-masters
    
    ## Memory and Disk
    vm_memory_high_watermark.relative = 0.6
    disk_free_limit.absolute = 1GB
    
    ## Networking
    listeners.tcp.default = 5672
    management.tcp.port = 15672
    
    ## Logging
    log.file.level = info
    log.console.level = info
