apiVersion: v1
kind: Service
metadata:
  name: spark-processor
  namespace: data-processing
  labels:
    app: spark-processor
spec:
  type: ClusterIP
  ports:
  - name: spark-ui
    port: 4040
    targetPort: 4040
    protocol: TCP
  - name: metrics
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: spark-processor
