apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless
  namespace: data-processing
  labels:
    app: mongodb
spec:
  clusterIP: None
  ports:
  - name: mongodb
    port: 27017
    targetPort: 27017
  selector:
    app: mongodb
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: data-processing
  labels:
    app: mongodb
spec:
  type: ClusterIP
  ports:
  - name: mongodb
    port: 27017
    targetPort: 27017
    protocol: TCP
  selector:
    app: mongodb
