[gateway]
34.14.74.12 ansible_user=ubuntu ansible_ssh_private_key_file=./id_rsa_gcp

[master]
10.240.0.10 ansible_user=ubuntu

[workers]
10.240.0.3 ansible_user=ubuntu
10.240.0.5 ansible_user=ubuntu
10.240.0.4 ansible_user=ubuntu

[all:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q ubuntu@34.14.74.12 -i ./id_rsa_gcp" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=60'
ansible_ssh_private_key_file=./id_rsa_gcp