apiVersion: v1
kind: Service
metadata:
  name: swagger-api
  namespace: data-processing
  labels:
    app: swagger-api
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: swagger-api
